### ISSUE TITLE
Some parameter(allowedTypes、isNeedVideoCamera、selectionLimit) settings do not work.

### ISSUE THREAD

**Issue by zhponng** [holyboom1/advanced_media_picker#3]
This is an amazing project. However, there are a few issues I'd like to report:

1. After setting *`allowedTypes`* to *`PickerAssetType.image`*, the toggle button for the file selector at the bottom of the popup cannot be hidden.
2. After setting *`isNeedVideoCamera`* to *`false`*, video recording is still possible in photo mode.
3. After setting *`selectionLimit`*, the maximum number of photos in photo mode is not limited.
4. Perhaps an option can be provided to not display the real-time preview of the camera in the image selection popup. This feature is great, but I'm concerned about potential performance and privacy issues in certain scenarios.

Looking forward to your response.

**Comment by holyboom1** [comment]
Hi @zhponng . 
Thanks for your feedback) 
1. You can disable the bottom bar function through the picker style settings.
2. I will check this behavior 
3. I will check this behavior 
4. I will add this functionality in the near future

Thank you!

**Comment by holyboom1** [comment]
fixed in release 0.0.12
